# Generated by Django 5.2.4 on 2025-07-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price_address_zip_and_more'),
    ]

    operations = [
        migrations.RunSQL(''' 
            INSERT INTO store_collection (title)
            VALUES ('collection')
        ''','''
            DELETE FROM store_collection 
            WHERE title = 'collection'
        ''')
    ]
 
