# Generated by Django 5.2.4 on 2025-07-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20250705_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
