# Generated by Django 5.2.4 on 2025-07-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('custom_cancel_order', 'Custom can cancel order')]},
        ),
    ]
